version: "3.8"

services:
  scraper:
    build: .
    volumes:
      - ./crawling_data:/app/crawling_data
      - ./logs:/app/logs
    environment:
      BASE_URL: ${BASE_URL:-http://host.docker.internal:1010}
      SHOP_NAME: ${SHOP_NAME}
      PROFILE_ID: ${PROFILE_ID}
      NUMPAGE: ${NUMPAGE:-1}
